FROM postgres

RUN apt-get update && apt-get upgrade -y && apt-get install -y python python-pip libpq-dev python-dev && apt-get clean

RUN pip install psycopg2-binary psycopg2

ENV POSTGRES_PASSWORD=1234

COPY schema.sql /docker-entrypoint-initdb.d/